#!/usr/bin/env python
# -*- coding: utf-8 -*-

import threading
import subprocess

from Cheese.cheese import CheeseBurger
from Cheese.resourceManager import ResMan

"""
File generated by Cheese Framework

main file of Cheese Application
"""

def runFileServer():
    subprocess.call(ResMan.joinPath(ResMan.resources(), "fileServer.bat"))

if __name__ == "__main__":
    CheeseBurger.init()

    x = threading.Thread(target=runFileServer)
    x.start()

    CheeseBurger.serveForever()